export interface PenguinFacility {
  id: string
  name: string
  type: "aquarium" | "zoo"
  prefecture: string
  region: string
  address: string
  lat: number
  lng: number
  penguinSpecies: string[]
  website?: string
}

export const regions = [
  "北海道",
  "東北",
  "関東",
  "中部",
  "近畿",
  "中国",
  "四国",
  "九州・沖縄",
] as const

export type Region = (typeof regions)[number]

export const penguinFacilities: PenguinFacility[] = [
  // 北海道
  {
    id: "asahiyama",
    name: "旭山動物園",
    type: "zoo",
    prefecture: "北海道",
    region: "北海道",
    address: "北海道旭川市東旭川町倉沼",
    lat: 43.7689,
    lng: 142.4756,
    penguinSpecies: ["キングペンギン", "ジェンツーペンギン", "フンボルトペンギン", "イワトビペンギン"],
    website: "https://www.city.asahikawa.hokkaido.jp/asahiyamazoo/",
  },
  {
    id: "otaru",
    name: "おたる水族館",
    type: "aquarium",
    prefecture: "北海道",
    region: "北海道",
    address: "北海道小樽市祝津3丁目303番地",
    lat: 43.2358,
    lng: 140.9678,
    penguinSpecies: ["フンボルトペンギン", "ジェンツーペンギン"],
    website: "https://otaru-aq.jp/",
  },
  {
    id: "noboribetsu",
    name: "登別マリンパークニクス",
    type: "aquarium",
    prefecture: "北海道",
    region: "北海道",
    address: "北海道登別市登別東町1丁目22",
    lat: 42.4108,
    lng: 141.1067,
    penguinSpecies: ["キングペンギン", "ジェンツーペンギン", "ケープペンギン"],
    website: "https://www.nixe.co.jp/",
  },
  // 東北
  {
    id: "sendai-umino-mori",
    name: "仙台うみの杜水族館",
    type: "aquarium",
    prefecture: "宮城県",
    region: "東北",
    address: "宮城県仙台市宮城野区中野4丁目6番地",
    lat: 38.2614,
    lng: 141.0067,
    penguinSpecies: ["フンボルトペンギン", "オウサマペンギン"],
    website: "http://www.uminomori.jp/",
  },
  {
    id: "katsuushima",
    name: "男鹿水族館GAO",
    type: "aquarium",
    prefecture: "秋田県",
    region: "東北",
    address: "秋田県男鹿市戸賀塩浜字壺ヶ沢93",
    lat: 39.9347,
    lng: 139.7069,
    penguinSpecies: ["ジェンツーペンギン", "フンボルトペンギン"],
    website: "https://www.gao-aqua.jp/",
  },
  {
    id: "aquamarine",
    name: "アクアマリンふくしま",
    type: "aquarium",
    prefecture: "福島県",
    region: "東北",
    address: "福島県いわき市小名浜字辰巳町50",
    lat: 36.9372,
    lng: 140.8981,
    penguinSpecies: ["ゴマフアザラシ"],
    website: "https://www.aquamarine.or.jp/",
  },
  // 関東
  {
    id: "ueno",
    name: "上野動物園",
    type: "zoo",
    prefecture: "東京都",
    region: "関東",
    address: "東京都台東区上野公園9-83",
    lat: 35.7164,
    lng: 139.7716,
    penguinSpecies: ["ケープペンギン", "フンボルトペンギン"],
    website: "https://www.tokyo-zoo.net/zoo/ueno/",
  },
  {
    id: "sumida",
    name: "すみだ水族館",
    type: "aquarium",
    prefecture: "東京都",
    region: "関東",
    address: "東京都墨田区押上1-1-2 東京スカイツリータウン・ソラマチ5F・6F",
    lat: 35.7101,
    lng: 139.8107,
    penguinSpecies: ["マゼランペンギン"],
    website: "https://www.sumida-aquarium.com/",
  },
  {
    id: "sunshine",
    name: "サンシャイン水族館",
    type: "aquarium",
    prefecture: "東京都",
    region: "関東",
    address: "東京都豊島区東池袋3-1 サンシャインシティ ワールドインポートマートビル屋上",
    lat: 35.7295,
    lng: 139.7193,
    penguinSpecies: ["ケープペンギン", "フンボルトペンギン"],
    website: "https://sunshinecity.jp/aquarium/",
  },
  {
    id: "shinagawa",
    name: "しながわ水族館",
    type: "aquarium",
    prefecture: "東京都",
    region: "関東",
    address: "東京都品川区勝島3-2-1",
    lat: 35.5898,
    lng: 139.7408,
    penguinSpecies: ["マゼランペンギン"],
    website: "https://www.aquarium.gr.jp/",
  },
  {
    id: "enoshima",
    name: "新江ノ島水族館",
    type: "aquarium",
    prefecture: "神奈川県",
    region: "関東",
    address: "神奈川県藤沢市片瀬海岸2-19-1",
    lat: 35.3101,
    lng: 139.4819,
    penguinSpecies: ["フンボルトペンギン"],
    website: "https://www.enosui.com/",
  },
  {
    id: "yokohama-hakkeijima",
    name: "横浜・八景島シーパラダイス",
    type: "aquarium",
    prefecture: "神奈川県",
    region: "関東",
    address: "神奈川県横浜市金沢区八景島",
    lat: 35.3361,
    lng: 139.6456,
    penguinSpecies: ["キングペンギン", "ジェンツーペンギン", "アデリーペンギン", "ケープペンギン"],
    website: "http://www.seaparadise.co.jp/",
  },
  {
    id: "kamogawa",
    name: "鴨川シーワールド",
    type: "aquarium",
    prefecture: "千葉県",
    region: "関東",
    address: "千葉県鴨川市東町1464-18",
    lat: 35.1056,
    lng: 140.1039,
    penguinSpecies: ["キングペンギン", "フンボルトペンギン"],
    website: "https://www.kamogawa-seaworld.jp/",
  },
  {
    id: "tobu",
    name: "東武動物公園",
    type: "zoo",
    prefecture: "埼玉県",
    region: "関東",
    address: "埼玉県南埼玉郡宮代町須賀110",
    lat: 36.0286,
    lng: 139.7289,
    penguinSpecies: ["フンボルトペンギン"],
    website: "https://www.tobuzoo.com/",
  },
  // 中部
  {
    id: "nagoya-port",
    name: "名古屋港水族館",
    type: "aquarium",
    prefecture: "愛知県",
    region: "中部",
    address: "愛知県名古屋市港区港町1番3号",
    lat: 35.0875,
    lng: 136.8781,
    penguinSpecies: ["エンペラーペンギン", "アデリーペンギン", "ジェンツーペンギン", "ヒゲペンギン"],
    website: "https://nagoyaaqua.jp/",
  },
  {
    id: "higashiyama",
    name: "東山動植物園",
    type: "zoo",
    prefecture: "愛知県",
    region: "中部",
    address: "愛知県名古屋市千種区東山元町3-70",
    lat: 35.1597,
    lng: 136.9756,
    penguinSpecies: ["フンボルトペンギン"],
    website: "https://www.higashiyama.city.nagoya.jp/",
  },
  {
    id: "noto-island",
    name: "のとじま水族館",
    type: "aquarium",
    prefecture: "石川県",
    region: "中部",
    address: "石川県七尾市能登島曲町15部40",
    lat: 37.1156,
    lng: 136.9917,
    penguinSpecies: ["フンボルトペンギン", "マゼランペンギン"],
    website: "https://www.notoaqua.jp/",
  },
  {
    id: "niigata",
    name: "新潟市水族館 マリンピア日本海",
    type: "aquarium",
    prefecture: "新潟県",
    region: "中部",
    address: "新潟県新潟市中央区西船見町5932-445",
    lat: 37.9147,
    lng: 139.0119,
    penguinSpecies: ["フンボルトペンギン", "イワトビペンギン"],
    website: "https://www.marinepia.or.jp/",
  },
  // 近畿
  {
    id: "kaiyukan",
    name: "海遊館",
    type: "aquarium",
    prefecture: "大阪府",
    region: "近畿",
    address: "大阪府大阪市港区海岸通1-1-10",
    lat: 34.6547,
    lng: 135.4289,
    penguinSpecies: ["キングペンギン", "イワトビペンギン", "アデリーペンギン"],
    website: "https://www.kaiyukan.com/",
  },
  {
    id: "tennoji",
    name: "天王寺動物園",
    type: "zoo",
    prefecture: "大阪府",
    region: "近畿",
    address: "大阪府大阪市天王寺区茶臼山町1-108",
    lat: 34.6514,
    lng: 135.5072,
    penguinSpecies: ["フンボルトペンギン"],
    website: "https://www.tennojizoo.jp/",
  },
  {
    id: "kyoto",
    name: "京都水族館",
    type: "aquarium",
    prefecture: "京都府",
    region: "近畿",
    address: "京都府京都市下京区観喜寺町35-1",
    lat: 34.9875,
    lng: 135.7472,
    penguinSpecies: ["ケープペンギン"],
    website: "https://www.kyoto-aquarium.com/",
  },
  {
    id: "kobe-oji",
    name: "神戸市立王子動物園",
    type: "zoo",
    prefecture: "兵庫県",
    region: "近畿",
    address: "兵庫県神戸市灘区王子町3-1",
    lat: 34.7131,
    lng: 135.2128,
    penguinSpecies: ["フンボルトペンギン"],
    website: "https://www.kobe-ojizoo.jp/",
  },
  {
    id: "suma",
    name: "神戸須磨シーワールド",
    type: "aquarium",
    prefecture: "兵庫県",
    region: "近畿",
    address: "兵庫県神戸市須磨区若宮町1丁目3-5",
    lat: 34.6356,
    lng: 135.1089,
    penguinSpecies: ["マゼランペンギン", "ケープペンギン"],
    website: "https://www.kobesuma-seaworld.jp/",
  },
  {
    id: "adventure-world",
    name: "アドベンチャーワールド",
    type: "zoo",
    prefecture: "和歌山県",
    region: "近畿",
    address: "和歌山県西牟婁郡白浜町堅田2399",
    lat: 33.6803,
    lng: 135.3553,
    penguinSpecies: ["エンペラーペンギン", "キングペンギン", "アデリーペンギン", "ジェンツーペンギン"],
    website: "https://www.aws-s.com/",
  },
  // 中国
  {
    id: "miyajima",
    name: "宮島水族館 みやじマリン",
    type: "aquarium",
    prefecture: "広島県",
    region: "中国",
    address: "広島県廿日市市宮島町10-3",
    lat: 34.2947,
    lng: 132.3172,
    penguinSpecies: ["フンボルトペンギン"],
    website: "https://miyajima-aqua.jp/",
  },
  {
    id: "shimonoseki",
    name: "下関市立しものせき水族館 海響館",
    type: "aquarium",
    prefecture: "山口県",
    region: "中国",
    address: "山口県下関市あるかぽーと6番1号",
    lat: 33.9536,
    lng: 130.9461,
    penguinSpecies: ["キングペンギン", "ジェンツーペンギン", "フンボルトペンギン", "イワトビペンギン", "マカロニペンギン"],
    website: "https://www.kaikyokan.com/",
  },
  // 四国
  {
    id: "shikoku",
    name: "四国水族館",
    type: "aquarium",
    prefecture: "香川県",
    region: "四国",
    address: "香川県綾歌郡宇多津町浜一番丁4",
    lat: 34.3058,
    lng: 133.8286,
    penguinSpecies: ["ケープペンギン"],
    website: "https://shikoku-aquarium.jp/",
  },
  {
    id: "tobe",
    name: "愛媛県立とべ動物園",
    type: "zoo",
    prefecture: "愛媛県",
    region: "四国",
    address: "愛媛県伊予郡砥部町上原町240",
    lat: 33.7847,
    lng: 132.8069,
    penguinSpecies: ["フンボルトペンギン"],
    website: "https://www.tobezoo.com/",
  },
  {
    id: "kochi",
    name: "高知県立のいち動物公園",
    type: "zoo",
    prefecture: "高知県",
    region: "四国",
    address: "高知県香南市野市町大谷738",
    lat: 33.5583,
    lng: 133.7067,
    penguinSpecies: ["フンボルトペンギン"],
    website: "https://noichizoo.or.jp/",
  },
  // 九州・沖縄
  {
    id: "marine-world",
    name: "マリンワールド海の中道",
    type: "aquarium",
    prefecture: "福岡県",
    region: "九州・沖縄",
    address: "福岡県福岡市東区西戸崎18-28",
    lat: 33.6656,
    lng: 130.3631,
    penguinSpecies: ["キングペンギン", "ジェンツーペンギン", "フンボルトペンギン"],
    website: "https://marine-world.jp/",
  },
  {
    id: "nagasaki-penguin",
    name: "長崎ペンギン水族館",
    type: "aquarium",
    prefecture: "長崎県",
    region: "九州・沖縄",
    address: "長崎県長崎市宿町3番地16",
    lat: 32.7778,
    lng: 129.9247,
    penguinSpecies: [
      "キングペンギン",
      "エンペラーペンギン",
      "ジェンツーペンギン",
      "ヒゲペンギン",
      "マカロニペンギン",
      "イワトビペンギン",
      "フンボルトペンギン",
      "ケープペンギン",
      "マゼランペンギン",
    ],
    website: "https://penguin-aqua.jp/",
  },
  {
    id: "umi-tamago",
    name: "大分マリーンパレス水族館 うみたまご",
    type: "aquarium",
    prefecture: "大分県",
    region: "九州・沖縄",
    address: "大分県大分市大字神崎字ウト3078-22",
    lat: 33.2506,
    lng: 131.7106,
    penguinSpecies: ["フンボルトペンギン"],
    website: "https://www.umitamago.jp/",
  },
  {
    id: "phoenix",
    name: "フェニックス自然動物園",
    type: "zoo",
    prefecture: "宮崎県",
    region: "九州・沖縄",
    address: "宮崎県宮崎市塩路浜山3083-42",
    lat: 31.9728,
    lng: 131.4647,
    penguinSpecies: ["フンボルトペンギン"],
    website: "https://www.miyazaki-city-zoo.jp/",
  },
  {
    id: "kagoshima",
    name: "平川動物公園",
    type: "zoo",
    prefecture: "鹿児島県",
    region: "九州・沖縄",
    address: "鹿児島県鹿児島市平川町5669-1",
    lat: 31.4847,
    lng: 130.5306,
    penguinSpecies: ["フンボルトペンギン"],
    website: "https://hirakawazoo.jp/",
  },
  {
    id: "churaumi",
    name: "沖縄美ら海水族館",
    type: "aquarium",
    prefecture: "沖縄県",
    region: "九州・沖縄",
    address: "沖縄県国頭郡本部町字石川424番地",
    lat: 26.6939,
    lng: 127.8775,
    penguinSpecies: [],
    website: "https://churaumi.okinawa/",
  },
]

export function getFacilitiesByRegion(region: Region): PenguinFacility[] {
  return penguinFacilities.filter((f) => f.region === region && f.penguinSpecies.length > 0)
}

export function getAllPenguinFacilities(): PenguinFacility[] {
  return penguinFacilities.filter((f) => f.penguinSpecies.length > 0)
}
